---

- name: Updating DuckDNS records
  get_url:
    url: "https://www.duckdns.org/update?domains={{ duckdns_domain }}&token={{ duckdns_token }}&ip={{ ansible_host }}"
    dest: /dev/null
  retries: 60
  delay: 10
  register: duckdns_update_result
  until: duckdns_update_result is not failed
  when: duckdns_token is defined and duckdns_domain is defined
