---

- name: Updating DuckDNS records
  uri:
    url: "https://www.duckdns.org/update?domains={{ duckdns_subdomain }}&token={{ duckdns_token }}&ip={{ ansible_host }}"
  retries: 20
  delay: 30
  register: duckdns_update_result
  until: duckdns_update_result is not failed
  when: duckdns_token is defined and duckdns_subdomain is defined
