---

- file:
    state: directory
    path: /opt/stacks/portainer/
    mode: '0600'
  run_once: true

- name: Copy portainer stack file
  copy:
    src: files/portainer.stack.yml
    dest: /opt/stacks/portainer/docker-compose.yml
    mode: '0600'
  run_once: true

- name: Create portainer secret
  docker_secret:
    name: portainer-pass
    data: "{{ admin_password | b64encode }}"
    data_is_b64: true
    state: present

- name: Deploy portainer stack
  docker_stack:
    state: present
    name: portainer
    compose:
      - /opt/stacks/portainer/docker-compose.yml
  environment:
    DOMAIN: "admin.{{ domain_name }}"
  run_once: true

- name: wait for portainer interface to become available
  uri:
    validate_certs: yes
    method: GET
    url: "https://portainer.admin.{{ domain_name }}"
    status_code: 200
  register: result
  until: result.status == 200
  retries: 60
  delay: 5
  run_once: true
