---

- name: Create admin password hash for stack
  set_fact:
    admin_password_hash: "{{ admin_password | password_hash('blowfish', rounds=12, salt=['proxy', fingerprint, filetime_result.stdout] | join('|') | hash('sha1') | truncate(22, True, '')) }}"
  run_once: true

- name: Create network for the reverse-proxy
  docker_network:
    state: present
    name: traefik-public
    scope: swarm
    driver: overlay
    attachable: yes
  run_once: true

- name: Create traefik secret
  docker_secret:
    name: traefik-pass
    data: "{{ ['admin', admin_password_hash] | join(':') | b64encode }}"
    data_is_b64: true
    state: present

- name: Copy proxy stack file
  copy:
    src: files/proxy.stack.yml
    dest: /opt/stacks/proxy.stack.yml
  run_once: true

- name: Deploy reverse-proxy stack
  docker_stack:
    state: present
    name: proxy
    compose:
      - /opt/stacks/proxy.stack.yml
  environment:
    EMAIL: "{{ ca_email }}"
    DOMAIN: "admin.{{ domain_name }}"
    CONSUL_REPLICAS: 3
    TRAEFIK_REPLICAS: 3
    CA_SERVER: "{{ ca_server }}"
  run_once: true
