---

- name: Create directory for docker-compose
  file:
    state: directory
    path: /opt/stacks/registry
    mode: '0600'

- name: Copy docker-compose file
  copy:
    src: files/registry.stack.yml
    dest: /opt/stacks/registry/docker-compose.yml
    mode: '0600'

- name: Deploy docker-compose file to swarm
  docker_stack:
    state: present
    name: registry
    compose:
      - /opt/stacks/registry/docker-compose.yml
  environment:
    DOMAIN: "{{ swarm_subdomain }}.{{ domain_name }}"
    REGISTRY_TITLE: "registry.{{ swarm_subdomain }}.{{ domain_name }}"
    REGISTRY_HTTP_SECRET: "{{ domain_name | hash('sha1') | truncate(10, True, '') }}"

- name: wait for registry to come up
  uri:
    validate_certs: yes
    method: GET
    url: "https://registry.{{ swarm_subdomain }}.{{ domain_name }}"
    status_code: 401
  register: result
  until: result.status == 401
  retries: 60
  delay: 5
  run_once: true
