---

- name: Create directory for docker-compose
  file:
    state: directory
    path: /opt/stacks/registry
    mode: '0600'

- name: Copy docker-compose file
  copy:
    src: files/registry.stack.yml
    dest: /opt/stacks/registry/docker-compose.yml
    mode: '0600'

- name: Deploy docker-compose file to swarm
  docker_stack:
    state: present
    name: registry
    compose:
      - /opt/stacks/registry/docker-compose.yml
  environment:
    ROUTERS_RULE: "Host(`{{ ['registry'] | product(swarm_hostnames) | map('join', '.') | join('`,`') }}`)"
    REGISTRY_TITLE: "{{ project_name | title }} Registry"
    REGISTRY_HTTP_SECRET: "{{ project_name | hash('sha1') | truncate(10, True, '') }}"

- name: wait for registry to come up
  uri:
    validate_certs: yes
    method: GET
    url: "https://{{ item }}/"
    status_code: [200, 401]
  register: result
  until: result.status in [200, 401]
  retries: 60
  delay: 5
  with_items: "{{ ['registry'] | product(swarm_hostnames) | map('join', '.') }}"
  run_once: true
  ignore_errors: yes
