---

- name: Create directory for docker-compose
  file:
    state: directory
    path: /opt/stacks/registry
    mode: '0600'

- name: Copy docker-compose file
  copy:
    src: files/registry.stack.yml
    dest: /opt/stacks/registry/docker-compose.yml
    mode: '0600'

- name: Deploy docker-compose file to swarm
  docker_stack:
    state: present
    name: registry
    compose:
      - /opt/stacks/registry/docker-compose.yml
  environment:
    DOMAIN: "{{ domain_name }}"
    REGISTRY_TITLE: "{{ domain_name }}"
    REGISTRY_HTTP_SECRET: "{{ domain_name | hash('sha1') | truncate(10, True, '') }}"

- name: Wait for registry to become available
  uri:
    validate_certs: no
    method: GET
    url: "https://registry.{{ domain_name }}"
    status_code: 401
  register: result
  until: result.status == 401
  retries: 60
  delay: 5
  run_once: true

- name: Login to registry
  docker_login:
    registry: "registry.{{ domain_name }}"
    username: "admin"
    password: "{{ admin_password }}"
  register: result
  changed_when: false
  retries: 20
  delay: 30
  until: not result.failed
