---

- name: Create admin password hash for stack
  set_fact:
    admin_password_hash: "{{ admin_password | password_hash('blowfish', rounds=12, salt=['swarmprom', fingerprint, filetime_result.stdout] | join('|') | hash('sha1') | truncate(22, True, '')) }}"
  run_once: true

- git:
    repo: 'https://github.com/stefanprodan/swarmprom.git'
    dest: /opt/stacks/swarmprom
    version: master
  run_once: true

- name: Copy swarmprom stack file
  copy:
    src: files/swarmprom.stack.yml
    dest: /opt/stacks/swarmprom/docker-compose.custom.yml
  run_once: true

- name: Deploy swarmprom stack
  docker_stack:
    state: present
    name: swarmprom
    compose:
      - /opt/stacks/swarmprom/docker-compose.custom.yml
  environment:
    ADMIN_USER: "admin"
    ADMIN_PASSWORD: "{{ admin_password }}"
    DOMAIN: "admin.{{ domain_name }}"
    TRAEFIK_PUBLIC_TAG: traefik-public
  run_once: true
