---

- name: Add labels to nodes
  docker_node:
    hostname: "{{ groups['managers'][0] }}"
    labels: "{'swarmpit.db-data': 'true', 'swarmpit.influx-data': 'true'}"
  loop: "{{ ansible_play_batch }}"
  when: inventory_hostname in groups['managers']
  run_once: true

- name: Copy swarmpit stack file
  copy:
    src: files/swarmpit.stack.yml
    dest: /opt/stacks/swarmpit.stack.yml
  run_once: true

- name: Deploy swarmpit stack
  docker_stack:
    state: present
    name: swarmpit
    compose:
      - /opt/stacks/swarmpit.stack.yml
  environment:
    ROUTERS_RULE: "Host(`{{ ['swarmpit'] | product(swarm_hostnames) | map('join', '.') | join('`,`') }}`)"
  run_once: true

- name: wait for swarmpit to become available
  uri:
    validate_certs: yes
    method: GET
    url: "https://{{ item }}/"
    status_code: [200, 401]
  register: result
  until: result.status in [200, 401]
  retries: 60
  delay: 15
  with_items: "{{ ['swarmpit'] | product(swarm_hostnames) | map('join', '.') }}"
  run_once: true
  ignore_errors: yes

- name: Create first admin account
  uri:
    validate_certs: yes
    method: POST
    body_format: json
    url: "https://swarmpit.{{ swarm_hostnames[0] }}/initialize"
    body: '{"username": "admin", "password": "{{ admin_password }}"}'
    status_code: [201, 403]
  run_once: true
  ignore_errors: yes
