---

- name: Copy swarmpit stack file
  copy:
    src: files/swarmpit.stack.yml
    dest: /opt/stacks/swarmpit.stack.yml
  run_once: true

- name: Deploy swarmpit stack
  docker_stack:
    state: present
    name: swarmpit
    compose:
      - /opt/stacks/swarmpit.stack.yml
  environment:
    DOMAIN: "admin.{{ domain_name }}"
  run_once: true

- name: get list of hosts that run a traefik instance
  shell:
    cmd: docker stack ps proxy |grep proxy_traefik |awk '{print $4}'
  register: result
  changed_when: false
  run_once: true
  when: "'managers' in group_names"

- name: set proxy_host to first entry
- set_fact:
    proxy_host: "{{ hostvars[result.stdout_lines[0]].ansible_host }}"

- name: wait for swarmpit to come up
  uri:
    headers:
      Host: "swarmpit.admin.{{ domain_name }}"
    validate_certs: no
    method: GET
    url: "https://{{ proxy_host }}/"
    status_code: 200
  register: result
  until: result.status == 200
  retries: 60
  delay: 5
  run_once: true

- name: Create first admin account
  uri:
    headers:
      Host: "swarmpit.admin.{{ domain_name }}"
    validate_certs: no
    method: POST
    body_format: json
    url: "https://{{ proxy_host }}/initialize"
    body: '{"username": "admin", "password": "{{ admin_password }}"}'
    status_code: [201, 403]
  register: result
  run_once: true
