---

- name: Copy swarmpit stack file
  copy:
    src: files/swarmpit.stack.yml
    dest: /opt/stacks/swarmpit.stack.yml
  run_once: true

- name: Deploy swarmpit stack
  docker_stack:
    state: present
    name: swarmpit
    compose:
      - /opt/stacks/swarmpit.stack.yml
  environment:
    DOMAIN: "admin.{{ domain_name }}"
  run_once: true

- name: wait for swarmpit to come up
  uri:
    validate_certs: yes
    method: GET
    url: "https://swarmpit.admin.{{ domain_name }}"
    status_code: 200
  register: result
  until: result.status == 200
  retries: 60
  delay: 10
  run_once: true

- name: Create first admin account
  uri:
    validate_certs: yes
    method: POST
    body_format: json
    url: "https://swarmpit.admin.{{ domain_name }}/initialize"
    body: '{"username": "admin", "password": "{{ admin_password }}"}'
    status_code: [201, 403]
  run_once: true
