---

- file:
    state: directory
    path: /opt/stacks/tests/
    mode: '0600'
  run_once: true

- name: Copy stack file
  copy:
    src: files/tests.stack.yml
    dest: /opt/stacks/tests/docker-compose.yml
    mode: '0600'
  run_once: true

- name: Deploy portainer stack
  docker_stack:
    state: present
    name: tests
    compose:
      - /opt/stacks/tests/docker-compose.yml
  environment:
    ROUTERS_RULE_APP1: "Host(`{{ ['app1'] | product(swarm_hostnames) | map('join', '.') | join('`,`') }}`)"
    ROUTERS_RULE_APP2: "Host(`{{ ['app2'] | product(swarm_hostnames) | map('join', '.') | join('`,`') }}`)"
    ROUTERS_RULE_APP3: "Host(`{{ ['app3'] | product(swarm_hostnames) | map('join', '.') | join('`,`') }}`)"
    ROUTERS_RULE_APP4: "Host(`{{ ['app4'] | product(swarm_hostnames) | map('join', '.') | join('`,`') }}`)"
  run_once: true

- name: wait for test services to become available
  uri:
    validate_certs: yes
    method: GET
    url: "https://{{ item }}.{{ swarm_hostnames[0] }}/"
    status_code: 200
  register: result
  until: result.status == 200
  retries: 60
  delay: 5
  with_items:
    - app1
    - app2
    - app3
    - app4
  run_once: true
