---

- name: Copy hello-world stack file
  copy:
    src: files/hello-world.stack.yml
    dest: /opt/stacks/hello-world.stack.yml
    mode: '0600'
  run_once: true

- name: Deploy hello-world stack
  docker_stack:
    state: present
    name: test-apps
    compose:
      - /opt/stacks/hello-world.stack.yml
  environment:
    DOMAIN: "apps.{{ domain_name }}"
  run_once: true

- name: Copy test-apps stack file
  copy:
    src: files/test-apps.stack.yml
    dest: /opt/stacks/test-apps.stack.yml
    mode: '0600'
  run_once: true

- name: Deploy test-apps stack
  docker_stack:
    state: present
    name: test-apps
    compose:
      - /opt/stacks/test-apps.stack.yml
  environment:
    DOMAIN: "apps.{{ domain_name }}"
  run_once: true
