---

- name: Get Let's Encrypts certificates
  hosts: managers[0]
  become: true
  roles:
    - get-certs
  tags: get-certs

- name: Clear ip at DuckDNS
  hosts: entrypoints
  become: true
  roles:
    - duckdns-remove
  vars_files:
    - vars/main.yml
  tags: duckdns
