---

- name: Wait for nodes to become available
  hosts: all
  tasks:
  - wait_for_connection:
      delay: 10
      timeout: 600
  tags: waiting

- name: Setup Ubuntu
  hosts: all
  become: true
  roles:
    - setup_ubuntu
  vars_files:
    - vars/main.yml
  tags: ubuntu

- name: Mount the BigStorage disk
  hosts: storage
  become: true
  tasks:
    - name: Mount big storage device
      mount:
        path: "/mnt/storage"
        src: "/dev/{{ storage_device }}"
        fstype: xfs
        opts: defaults
        state: present
      when: storage_device is defined
  tags: storage

- name: Install Tinc
  hosts: tinc_vpn_mesh
  become: true
  roles:
    - tinc
  vars_files:
    - vars/main.yml
  tags: tinc

- name: Install Docker
  hosts: docker_swarm
  become: true
  roles:
    - docker
  vars_files:
    - vars/main.yml
  tags: docker

- name: Install Docker Machine and Virtualbox
  hosts: docker_machine_hosts
  become: true
  roles:
    - docker-machine
  vars_files:
    - vars/main.yml
  tags: docker-machine

- name: Setup Docker Swarm
  hosts: docker_swarm
  become: true
  roles:
    - swarm
  vars_files:
    - vars/main.yml
  tags: swarm

- name: Deploy stacks
  hosts: docker_swarm_manager
  become: true
  roles:
    - stacks
  vars_files:
    - vars/main.yml
  tags: stacks

- name: Register ip at DuckDNS
  hosts: domain_name_targets
  become: true
  roles:
    - duckdns
  vars_files:
    - vars/main.yml
  tags: duckdns
