---

- name: Wait for nodes to become available
  hosts: all
  any_errors_fatal: true
  gather_facts: no
  tasks:
  - wait_for_connection:
      delay: 10
      timeout: 600
  tags: waiting

- name: Get Let's Encrypts certificates
  hosts: managers[0]
  any_errors_fatal: true
  become: true
  vars_files:
    - vars/main.yml
    - secrets/vars.yml
  roles:
    - get-certs
  tags: get-certs

- name: Clear ip at DuckDNS
  hosts: duckdns
  any_errors_fatal: true
  become: true
  roles:
    - duckdns-remove
  vars_files:
    - vars/main.yml
    - secrets/vars.yml
  tags: duckdns
