---

- name: Wait for nodes to become available
  hosts: all
  tasks:
  - wait_for_connection:
      delay: 10
      timeout: 600
  tags: waiting

- name: Setup Ubuntu
  hosts: all
  become: true
  roles:
    - setup_ubuntu
  vars_files:
    - vars/main.yml
  tags: ubuntu

- name: Register ip at DuckDNS
  hosts: all
  become: true
  roles:
    - duckdns
  vars_files:
    - vars/main.yml
  tags: duckdns

- name: Install Tinc
  hosts: vpn_mesh
  become: true
  roles:
    - tinc
  vars_files:
    - vars/main.yml
  tags: tinc

- name: Install Glusterfs
  hosts: glusterpool
  become: true
  vars_files:
    - vars/main.yml
  roles:
    - glusterfs-server
  tags:
    - glusterfs

- name: Install Glusterfs
  hosts: swarm
  become: true
  vars_files:
    - vars/main.yml
  roles:
    - glusterfs-client
  tags:
    - glusterfs

- name: Install Docker
  hosts: swarm
  become: true
  roles:
    - docker
  vars_files:
    - vars/main.yml
  tags: docker

- name: Setup Docker Swarm
  hosts: swarm
  become: true
  roles:
    - swarm
  vars_files:
    - vars/main.yml
  tags: swarm

- name: Deploy stacks
  hosts: managers[0]
  become: true
  roles:
    - stacks
  vars_files:
    - vars/main.yml
  tags: stacks

- name: Store registry login data on nodes
  hosts: swarm
  become: true
  roles:
    - registry-login
  vars_files:
    - vars/main.yml
  tags: stacks
