---

- name: Wait for nodes to become available
  hosts: all
  any_errors_fatal: true
  gather_facts: no
  tasks:
  - wait_for_connection:
      delay: 10
      timeout: 600
  - action: ping
  tags: waiting

- name: Setup Ubuntu
  hosts: all
  any_errors_fatal: true
  become: true
  roles:
    - setup_ubuntu
  vars_files:
    - vars/main.yml
    - secrets/vars.yml
  tags: ubuntu

- name: Register ip at DuckDNS
  hosts: duckdns
  any_errors_fatal: true
  become: true
  roles:
    - duckdns
  vars_files:
    - vars/main.yml
    - secrets/vars.yml
  tags: duckdns

- name: Install Tinc
  hosts: vpn_mesh
  any_errors_fatal: true
  become: true
  roles:
    - tinc
  vars_files:
    - vars/main.yml
    - secrets/vars.yml
  tags: tinc

- name: Install Glusterfs servers
  hosts: glusterpool
  any_errors_fatal: true
  become: true
  vars_files:
    - vars/main.yml
    - secrets/vars.yml
  roles:
    - glusterfs-server
  tags:
    - glusterfs

- name: Install Glusterfs clients
  hosts: swarm
  any_errors_fatal: true
  become: true
  vars_files:
    - vars/main.yml
    - secrets/vars.yml
  roles:
    - glusterfs-client
  tags:
    - glusterfs

- name: Install Docker
  hosts: swarm
  any_errors_fatal: true
  become: true
  roles:
    - docker
  vars_files:
    - vars/main.yml
    - secrets/vars.yml
  tags: docker

- name: Setup Docker Swarm
  hosts: swarm
  any_errors_fatal: true
  become: true
  roles:
    - swarm
  vars_files:
    - vars/main.yml
    - secrets/vars.yml
  tags: swarm

- name: Install Syncthing
  hosts: swarm
  any_errors_fatal: true
  become: true
  vars_files:
    - vars/main.yml
    - secrets/vars.yml
  roles:
    - syncthing
  tags:
    - syncthing

- name: Deploy stacks
  hosts: managers[0]
  any_errors_fatal: true
  become: true
  roles:
    - stacks
  vars_files:
    - vars/main.yml
    - secrets/vars.yml
  tags: stacks

- name: Store registry login data on nodes
  hosts: swarm
  any_errors_fatal: true
  become: true
  roles:
    - registry-login
  vars_files:
    - vars/main.yml
    - secrets/vars.yml
  tags: stacks

- name: Display urls of deployed swarm services
  hosts: swarm
  any_errors_fatal: true
  become: true
  roles:
    - output-service-urls
  vars_files:
    - vars/main.yml
    - secrets/vars.yml
  tags: urls
