---

- name: Get Let's Encrypts certificates
  hosts: managers[0]
  any_errors_fatal: true
  become: true
  vars_files:
    - vars/main.yml
    - secrets/vars.yml
  roles:
    - get-certs
  tags: get-certs
