---

- name: install glusterfs-client
  apt:
    name: glusterfs-client
    state: present

- name: make glusterfs mount dir
  file:
    path: "/mnt/gluster0"
    state: directory

- name: mount glusterfs volume gluster0
  mount:
    path: "/mnt/gluster0"
    src: "{{ ansible_hostname if ansible_hostname in groups.glusterpool else groups.glusterpool[0] }}:/gluster0"
    fstype: glusterfs
    opts: "defaults,_netdev"
    state: mounted
