---

sys_packages:
  - curl
  - nano
  - git
  - python3
  - python3-pip
  - net-tools
  - iputils-ping
  - ferm
  - rsyslog
  - rsync
  - apt-transport-https

remove_packages:
  - iptables-persistent
  - netfilter-persistent
  - ufw
