version: '3.7'

services:

  hello-world:
    image: tutum/hello-world:latest
    networks:
      - traefik-public
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 32M
        reservations:
          cpus: '0.1'
          memory: 16M
      labels:
        - traefik.frontend.rule=Host:helloworld.${DOMAIN?Variable DOMAIN not set}
        - traefik.enable=true
        - traefik.port=80
        - traefik.tags=traefik-public
        - traefik.docker.network=traefik-public
        - traefik.frontend.entryPoints=http,https
        - traefik.frontend.redirect.entryPoint=https

networks:
  traefik-public:
    external: true
