version: "3.8"

services:
  agent:
    image: portainer/agent:linux-amd64-2.4.0-alpine
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent-network
    deploy:
      mode: global
      resources:
        limits:
          cpus: '0.02'
          memory: 32M
        reservations:
          cpus: '0.01'
          memory: 16M
      placement:
        constraints:
          - node.platform.os == linux

  portainer:
    image: portainer/portainer-ce:linux-amd64-2.5.1-alpine
    container_name: portainer
    restart: unless-stopped
    command: -H tcp://tasks.agent:9001 --tlsskipverify --admin-password-file /run/secrets/portainer-pass
    depends_on:
      - agent
    volumes:
      - portainer_data:/data
    networks:
      - agent-network
      - traefik-public
    secrets:
      - portainer-pass
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: '0.05'
          memory: 64M
        reservations:
          cpus: '0.01'
          memory: 32M
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.portainer.loadbalancer.server.port=9000"
        - "traefik.http.routers.portainer.rule=${ROUTERS_RULE?Variable ROUTERS_RULE not set}"
        - "traefik.http.routers.portainer.entrypoints=websecure"
        - "traefik.http.routers.portainer.tls=true"
        - "traefik.http.routers.portainer.tls.certresolver=myresolver"
        - "traefik.http.routers.portainer.middlewares=https-redirect@file,security-headers@file"

networks:
  agent-network:
    driver: overlay
    attachable: true
  traefik-public:
    external: true

volumes:
  portainer_data:

secrets:
  portainer-pass:
    external: true
