version: '3.7'

services:
  agent:
    image: portainer/agent:1.5.1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent-network
    deploy:
      mode: global
      placement:
        constraints:
          - node.platform.os == linux

  portainer:
    image: portainer/portainer:1.23.2
    container_name: portainer
    restart: unless-stopped
    command: -H tcp://tasks.agent:9001 --tlsskipverify --admin-password-file /run/secrets/portainer-pass
#    ports:
#      - target: 9000
#        published: 9000
#        protocol: tcp
#        mode: host
    volumes:
      - portainer_data:/data
    networks:
      - agent-network
      - traefik-public
    secrets:
      - portainer-pass
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
          - node.labels.portainer-frontend == true
      labels:
        - traefik.frontend.rule=Host:portainer.${DOMAIN?Variable DOMAIN not set}
        - traefik.enable=true
        - traefik.port=9000
        - traefik.tags=traefik-public
        - traefik.docker.network=traefik-public
        - traefik.frontend.entryPoints=http,https
        - traefik.frontend.redirect.entryPoint=https

networks:
  agent-network:
    driver: overlay
    attachable: true
  traefik-public:
    external: true

volumes:
  portainer_data:

secrets:
  portainer-pass:
    external: true
