version: '3.7'

services:

  consul-leader:
    image: consul:1.7.3
    command: agent -server -client=0.0.0.0 -bootstrap -ui
    volumes:
      - consul-data-leader:/consul/data
    environment:
      - CONSUL_BIND_INTERFACE=eth0
      - 'CONSUL_LOCAL_CONFIG={"leave_on_terminate": true}'
    networks:
      - consul-network
      - traefik-public
    secrets:
      - traefik-pass
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 64M
      labels:
        - traefik.enable=true
        - traefik.frontend.rule=Host:consul.${DOMAIN?Variable DOMAIN not set}
        - traefik.port=8500
        - traefik.tags=traefik-public
        - traefik.docker.network=traefik-public
        - traefik.frontend.entryPoints=http,https
        - traefik.frontend.redirect.entryPoint=https
        - traefik.frontend.auth.basic.usersFile=/run/secrets/traefik-pass

  consul-replica:
    image: consul:1.7.3
    command: agent -server -client=0.0.0.0 -retry-join="consul-leader"
    volumes:
      - consul-data-replica:/consul/data
    environment:
      - CONSUL_BIND_INTERFACE=eth0
      - 'CONSUL_LOCAL_CONFIG={"leave_on_terminate": true}'
    networks:
      - consul-network
    deploy:
      replicas: ${CONSUL_REPLICAS:-3}
      placement:
        preferences:
          - spread: node.id
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 64M

  docker-socket:
    image: tecnativa/docker-socket-proxy
    networks:
      - socket-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      CONTAINERS: 1
      NETWORKS: 1
      SERVICES: 1
      SWARM: 1
      TASKS: 1
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
    logging:
      options:
        max-size: "500k"

  traefik:
    image: traefik:v1.7
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
#      - target: 8080
#        published: 8080
#        mode: host
    deploy:
      replicas: ${TRAEFIK_REPLICAS:-3}
      placement:
        preferences:
          - spread: node.id
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 128M
      labels:
        - traefik.frontend.rule=Host:traefik.${DOMAIN?Variable DOMAIN not set}
        - traefik.enable=true
        - traefik.port=8080
        - traefik.tags=traefik-public
        - traefik.docker.network=traefik-public
        - traefik.frontend.entryPoints=http,https
        - traefik.frontend.redirect.entryPoint=https
        - traefik.frontend.auth.basic.usersFile=/run/secrets/traefik-pass
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      --docker
      --docker.endpoint=http://docker-socket:2375
      --docker.swarmmode
      --docker.watch
      --docker.exposedbydefault=false
      --constraints=tag==traefik-public
      --entrypoints='Name:http Address::80'
      --entrypoints='Name:https Address::443 TLS'
      --consul
      --consul.endpoint="consul-leader:8500"
      --acme
      --acme.email=${EMAIL}
      --acme.storage="traefik/acme/account"
      --acme.entryPoint=https
      --acme.httpChallenge.entryPoint=http
      --acme.onhostrule=true
      --acme.acmelogging=true
      --logLevel=INFO
      --accessLog
      --api
      --acme.caServer=${CA_SERVER:-"https://acme-v02.api.letsencrypt.org/directory"}
    networks:
      - traefik-public
      - socket-network
    depends_on:
      - docker-socket
      - consul-leader
    secrets:
      - traefik-pass

volumes:
  consul-data-leader:
  consul-data-replica:

networks:
  traefik-public:
    external: true
  consul-network:
    driver: overlay
  socket-network:
    driver: overlay

secrets:
  traefik-pass:
    external: true
