version: '3.7'

services:

  consul-leader:
    image: consul:1.8.3
    command: agent -server -client=0.0.0.0 -bootstrap -ui
    ports:
      - target: 8500
        published: 8500
        protocol: tcp
        mode: ingress
    volumes:
      - consul-data-leader:/consul/data
    environment:
      - CONSUL_BIND_INTERFACE=eth0
      - 'CONSUL_LOCAL_CONFIG={"leave_on_terminate": true}'
    networks:
      - consul-network
      - traefik-public
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 64M
      labels:
        - traefik.frontend.rule=Host:consul.${DOMAIN?Variable DOMAIN not set}
        - traefik.enable=true
        - traefik.port=8500
        - traefik.tags=traefik-public
        - traefik.docker.network=traefik-public
        - traefik.frontend.entryPoints=http,https
        - traefik.frontend.redirect.entryPoint=https
        - traefik.frontend.auth.basic.usersFile=/run/secrets/traefik-pass

  consul-replica:
    image: consul:1.8.3
    command: agent -server -client=0.0.0.0 -retry-join="consul-leader"
    volumes:
      - consul-data-replica:/consul/data
    environment:
      - CONSUL_BIND_INTERFACE=eth0
      - 'CONSUL_LOCAL_CONFIG={"leave_on_terminate": true}'
    networks:
      - consul-network
    deploy:
      mode: replicated
      replicas: ${CONSUL_REPLICAS:-3}
      placement:
        preferences:
          - spread: node.id
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 64M

  certs-dumper:
    image: ldez/traefik-certs-dumper:v2.7.0
    entrypoint: traefik-certs-dumper kv consul --endpoints consul-leader:8500 --watch --prefix traefik --suffix /acme/account/object --dest /data/certs
    volumes:
      - certs-backup:/data
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        reservations:
          cpus: '0.1'
          memory: 8M
        limits:
          cpus: '0.1'
          memory: 8M
    networks:
      - consul-network
    depends_on:
      - consul-leader

volumes:
  consul-data-leader:
  consul-data-replica:
  certs-backup:

networks:
  traefik-public:
    external: true
  consul-network:
    driver: overlay
    attachable: true
