version: '3.7'

services:

  docker-socket:
    image: tecnativa/docker-socket-proxy
    networks:
      - socket-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      BUILD: 0
      COMMIT: 0
      CONFIGS: 0
      CONTAINERS: 1
      DISTRIBUTION: 0
      EXEC: 0
      IMAGES: 0
      INFO: 0
      NETWORKS: 1
      NODES: 0
      PLUGINS: 0
      SERVICES: 1
      SESSION: 0
      SWARM: 1
      SYSTEM: 0
      TASKS: 1
      VOLUMES: 0
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: '0.05'
          memory: 16M
        reservations:
          cpus: '0.01'
          memory: 8M
    logging:
      options:
        max-size: "500k"

  traefik:
    image: traefik:v1.7.25
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
#      - target: 8080
#        published: 8080
#        mode: host
    networks:
      - socket-network
      - consul-network
      - traefik-public
    depends_on:
      - docker-socket
      - consul-leader
    secrets:
      - traefik-pass
    command:
      --consul
      --consul.endpoint="consul-leader:8500"
      --docker
      --docker.endpoint=http://docker-socket:2375
      --docker.swarmmode
      --docker.watch
      --docker.exposedbydefault=false
      --constraints=tag==traefik-public
      --entrypoints='Name:http Address::80'
      --entrypoints='Name:https Address::443 TLS'
      --acme
      --acme.email=${EMAIL}
      --acme.storage="traefik/acme/account"
      --acme.entryPoint=https
      --acme.httpChallenge.entryPoint=http
      --acme.ondemand=true
      --acme.onhostrule=true
      --acme.acmelogging=true
      --logLevel=INFO
      --accessLog
      --api
      --acme.caServer=${CA_SERVER:-"https://acme-staging-v02.api.letsencrypt.org/directory"}
    deploy:
      labels:
        - traefik.frontend.rule=Host:traefik.${DOMAIN?Variable DOMAIN not set}
        - traefik.enable=true
        - traefik.port=8080
        - traefik.tags=traefik-public
        - traefik.docker.network=traefik-public
        - traefik.frontend.entryPoints=http,https
        - traefik.frontend.redirect.entryPoint=https
        - traefik.frontend.auth.basic.usersFile=/run/secrets/traefik-pass
      mode: global
      placement:
        constraints:
          - node.labels.traefik == true
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 128M

networks:
  traefik-public:
    external: true
  consul-network:
    driver: overlay
    attachable: true
  socket-network:
    driver: overlay

secrets:
  traefik-pass:
    external: true
