version: "3.7"

services:

  registry:
    restart: always
    image: registry:2.7.1
    environment:
      - REGISTRY_HTTP_SECRET=${REGISTRY_HTTP_SECRET?Variable REGISTRY_HTTP_SECRET not set}
      - REGISTRY_STORAGE_DELETE_ENABLED=true
    volumes:
      - registry-data:/var/lib/registry
    networks:
      - registry-network
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.2'
          memory: 64M
        reservations:
          cpus: '0.1'
          memory: 32M

  registry-ui:
    restart: always
    image: joxit/docker-registry-ui:static
    environment:
      - DELETE_IMAGES=true
      - REGISTRY_TITLE=${REGISTRY_TITLE?Variable REGISTRY_TITLE not set}
      - REGISTRY_URL=http://registry:5000
    depends_on:
      - registry
    networks:
      - registry-network
      - traefik-public
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.2'
          memory: 64M
        reservations:
          cpus: '0.1'
          memory: 32M
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.registry.loadbalancer.server.port=80"
        - "traefik.http.routers.registry.rule=Host(`registry.${DOMAIN?Variable DOMAIN not set}`)"
        - "traefik.http.routers.registry.entrypoints=websecure"
        - "traefik.http.routers.registry.tls=true"
        - "traefik.http.routers.registry.tls.certresolver=myresolver"
        - "traefik.http.routers.registry.middlewares=auth-admin,https-redirect@file,security-headers@file"

volumes:
  registry-data:

networks:
  traefik-public:
    external: true
  registry-network:
    driver: overlay
