version: '3.8'

services:
  app:
    image: swarmpit/swarmpit:1.9
    environment:
      - SWARMPIT_DB=http://db:5984
      - SWARMPIT_INFLUXDB=http://influxdb:8086
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - net
      - traefik-public
    depends_on:
      - db
      - influxdb
      - agent
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.05'
          memory: 256M
        reservations:
          cpus: '0.01'
          memory: 128M
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.swarmpit.loadbalancer.server.port=8080"
        - "traefik.http.routers.swarmpit.rule=${ROUTERS_RULE?Variable ROUTERS_RULE not set}"
        - "traefik.http.routers.swarmpit.entrypoints=websecure"
        - "traefik.http.routers.swarmpit.tls=true"
        - "traefik.http.routers.swarmpit.tls.certresolver=myresolver"
        - "traefik.http.routers.swarmpit.middlewares=https-redirect@file,security-headers@file"

  db:
    image: couchdb:2.3.0
    volumes:
      - db-data:/opt/couchdb/data
    networks:
      - net
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.02'
          memory: 128M
        reservations:
          cpus: '0.01'
          memory: 32M
      placement:
        constraints:
          - node.labels.swarmpit.db-data == true

  influxdb:
    image: influxdb:1.7
    volumes:
      - influx-data:/var/lib/influxdb
    networks:
      - net
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.02'
          memory: 64M
        reservations:
          cpus: '0.01'
          memory: 32M
      placement:
        constraints:
          - node.labels.swarmpit.influx-data == true

  agent:
    image: swarmpit/agent:2.2
    environment:
      - DOCKER_API_VERSION=1.35
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - net
    deploy:
      mode: global
      labels:
        swarmpit.agent: 'true'
      resources:
        limits:
          cpus: '0.02'
          memory: 16M
        reservations:
          cpus: '0.01'
          memory: 8M

networks:
  net:
    driver: overlay
    attachable: true
  traefik-public:
    external: true

volumes:
  db-data:
    driver: local
  influx-data:
    driver: local
