[providers.file]
  [http.middlewares]
    [http.middlewares.https-redirect.redirectscheme]
      scheme = "https"
    [http.middlewares.security-headers.headers]
      # CORS
      #AccessControlAllowMethods = ["GET", "POST", "OPTIONS", "PUT", "POST"]
      AccessControlAllowOrigin = "origin-list-or-null"
      AccessControlMaxAge = 100
      #AddVaryHeader = true
      BrowserXssFilter = true
      ContentTypeNosniff = true
      ForceSTSHeader = true
      FrameDeny = true
      SSLRedirect = true
      STSIncludeSubdomains = true
      STSPreload = true
      ContentSecurityPolicy = "default-src 'self'; connect-src 'self' ; base-uri 'none'; base-uri 'self' ; script-src 'self'; style-src 'unsafe-inline' 'self'; style-src-elem 'self' 'unsafe-inline'; font-src 'self' 'unsafe-inline'; object-src 'self'; media-src 'self'; img-src 'self' data: blob: ; frame-src 'self' "
      CustomFrameOptionsValue = "SAMEORIGIN"
      ReferrerPolicy = "same-origin"
      #FeaturePolicy = "vibrate 'self'"
      STSSeconds = 315360000

[tls]
  [tls.options]
    [tls.options.default]
      minVersion = "VersionTLS12"
      sniStrict = true
      cipherSuites = [
        "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
        "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
        "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
        "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384",
        "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305",
        "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305",

        "TLS_AES_128_GCM_SHA256",
        "TLS_AES_256_GCM_SHA384",
        "TLS_CHACHA20_POLY1305_SHA256",

        # TLS_FALLBACK_SCSV isn't a standard cipher suite but an indicator
        # that the client is doing version fallback. See RFC 7507.
        "TLS_FALLBACK_SCSV" # Client is doing version fallback. See RFC 7507.
      ]
