---

- name: Wait for registry to become available
  uri:
    validate_certs: no
    method: GET
    url: "https://registry.{{ swarm_subdomain }}.{{ domain_name }}"
    status_code: 401
  register: result
  until: result.status == 401
  retries: 60
  delay: 5

- name: Login to registry
  docker_login:
    registry: "registry.{{ swarm_subdomain }}.{{ domain_name }}"
    username: "admin"
    password: "{{ admin_password }}"
  register: result
  changed_when: false
  retries: 20
  delay: 30
  until: not result.failed
