---

- name: Upgrade
  apt:
    upgrade: "safe"
    force_apt_get: yes
    update_cache: yes
    cache_valid_time: 3600
  register: apt_action
  retries: 100
  until: apt_action is success or ('Failed to lock apt for exclusive operation' not in apt_action.msg and '/var/lib/dpkg/lock' not in apt_action.msg)

- name: Check if reboot required
  stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: Reboot if required
  reboot:
    connect_timeout: 10
    post_reboot_delay: 10
    reboot_timeout: 600
  when: reboot_required_file.stat.exists == true
