---

- name: Check that the acme.json exists
  stat:
    path: "/mnt/gluster-admin/proxy_letsencrypt/acme.json"
  register: stat_result

- fetch:
    src: "/mnt/gluster-admin/proxy_letsencrypt/acme.json"
    dest: "secrets/backups/{{ project_name }}-{{ services_subdomain }}/acme.json"
    flat: yes
  when: stat_result.stat.exists
