---

- name: install glusterfs-server
  apt:
    name: glusterfs-server
    state: present

- name: Ensure that the glusterfs service is enabled and started at boot time
  service:
    name: glusterd
    enabled: yes
    state: started

- include_tasks: firewall.yml

- name: add peers to gluster cluster
  gluster_peer:
    state: present
    nodes: "{{ play_hosts }}"
  delegate_to: "{{ play_hosts | first }}"

- name: create glusterfs brick dirs
  file:
    path: /data/{{ item }}/brick
    state: directory
  loop:
    - gluster-admin
    - gluster-apps

- name: create gluster volumes
  gluster_volume:
    state: present
    name: "{{ item }}"
    bricks: "/data/{{ item }}/brick"
    replicas: "{{ play_hosts|length|int if play_hosts|length > 1 else 0 }}"
    cluster: "{{ play_hosts }}"
    transport: tcp
    force: yes
    start_on_create: yes
    options:
      { performance.cache-size: 128MB,
        write-behind: 'off',
        quick-read: 'on'
      }
  loop:
    - gluster-admin
    - gluster-apps
  run_once: true

- name: start gluster volume
  gluster_volume:
    state: started
    rebalance: yes
    name: "{{ item }}"
  loop:
    - gluster-admin
    - gluster-apps
