---

- name: Install aptitude using apt
  apt:
    name: aptitude
    state: latest
    update_cache: yes
    force_apt_get: yes
  tags: docker

- name: Install required system packages
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop:
    - apt-transport-https
    - ca-certificates
    - software-properties-common
  tags: docker

- pip:
    name:
      - docker
      - jsondiff
    state: latest
  tags: docker

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  tags: docker

- name: Add Docker Repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename|lower }} stable"
    state: present
    mode: "0644"
  tags: docker

- name: Update apt and install docker-ce
  apt:
    update_cache: yes
    name: "{{ item }}"
    state: latest
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-compose
  tags: docker

- name: Add user to 'docker' group
  user:
    name: "{{ create_user }}"
    groups: docker
    append: yes

- name: Configure Docker daemon options
  template:
    src: "daemon.json.j2"
    dest: "/etc/docker/daemon.json"
    owner: "root"
    group: "root"
    mode: "0644"
  notify:
    - restart docker
