---

- file:
    state: directory
    path: /var/syncthing
    mode: '0700'
    owner: syncthing
    group: syncthing

- file:
    state: directory
    path: /var/syncthing/{{ item }}
    mode: '0700'
    owner: syncthing
    group: syncthing
  with_items:
    - swarm-management

- pip:
    name: lxml
    state: latest

- xml:
    path: /home/syncthing/.config/syncthing/config.xml
    xpath: /configuration/device
    content: attribute
  register: xmlresponse

- set_fact:
    syncthing_device_id: "{{ item.device.id }}"
  when: item.device.name == ansible_hostname
  loop: "{{ xmlresponse.matches }}"
  no_log: yes

- template:
    src: config.xml.j2
    dest: /home/syncthing/.config/syncthing/config.xml
    owner: syncthing
    group: syncthing
    mode: '0600'
  vars:
    folders:
      - swarm-management
  notify: restart syncthing
