---

- name: Import Syncthing GPG key to apt
  apt_key:
    url: https://syncthing.net/release-key.gpg
    state: present

- name: Add Syncthing repository
  apt_repository:
    repo: 'deb https://apt.syncthing.net/ syncthing stable'
    state: present
    update_cache: yes

- name: Install Syncthing from Syncthing repository
  apt:
    name: syncthing
    state: present
    update_cache: yes

- name: Install service
  copy:
    src: syncthing.service
    dest: /etc/systemd/system/syncthing.service
    mode: 755
  register: systemd_conf

- name: Start service
  service:
    name: syncthing
    enabled: yes
    state: started

- name: Restart service
  service:
    name: syncthing
    state: restarted
  when: systemd_conf.changed

- name: Wait until configfile becomes available
  wait_for:
    path: /root/.config/syncthing/config.xml
